set nocompatible              " be iMproved, required
filetype off                  " required
filetype plugin on

"""" vim-plug
call plug#begin('~/.config/nvim/plugged')
Plug 'vimwiki/vimwiki'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'liuchengxu/space-vim-dark'
Plug 'unblevable/quick-scope'       " Plug
call plug#end()

filetype plugin indent on
" show existing tab with 4 spaces width      " To ignore plugin indent changes, instead use:
set tabstop=4                                "filetype plugin on
" when indenting with '>', use 4 spaces width"
set shiftwidth=4                             " Brief help
set expandtab

set number
set relativenumber
set nowrap

syntax on
"au BufNewFile,BufRead *.launch set filetype=xml
au BufReadPost *.launch set syntax=xml
au BufReadPost *.inc set syntax=cpp

set clipboard=unnamedplus
"set colorcolumn=80
set list
set listchars=tab:▸\ ,trail:_ list
set ruler
set so=20

" clear last search highlighting
map <Space> :noh<cr>

filetype indent on
set smartindent

" vimwiki/vimwiki
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]

"set ttymouse=xterm2
set mouse=a

" fzf
set rtp+=~/.fzf
nnoremap <C-p> :Files ~/ws/aquanaut/src<Cr>
nnoremap <C-g> :Rg<Cr>

let g:time_stamp_enabled = 0
command! TimeStampToggle let g:time_stamp_enabled = !g:time_stamp_enabled

inoremap <expr> <CR> g:time_stamp_enabled ? "\<ESC>:call TimeStamp()\<CR>a" : "\<CR>"

function! TimeStamp()
     let l:current_time = strftime("%H:%M:%S")
     execute "normal! 0i\<SPACE>\<ESC>0dwi\
          \<C-R>=l:current_time\<CR>\
          \<SPACE>\<SPACE>—\<SPACE>\<SPACE>\<ESC>o\<SPACE>\<SPACE>\<SPACE>\<SPACE>\
          \<SPACE>\<SPACE>\<SPACE>\<SPACE>\<SPACE>\<SPACE>\<SPACE>\<SPACE>\<SPACE>"

endfunction

" cya arrow keys
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

set cmdwinheight=6

color space-vim-dark
hi Normal ctermbg=NONE guibg=NONE
hi LineNr ctermbg=NONE guibg=NONE
