txtrst="$(tput sgr 0 2>/dev/null || echo '\e[0m')"

txtblk="$(tput setaf 0 2>/dev/null || echo '\e[0;30m')"
txtred="$(tput setaf 1 2>/dev/null || echo '\e[0;31m')"
txtgrn="$(tput setaf 2 2>/dev/null || echo '\e[0;32m')"
txtylw="$(tput setaf 3 2>/dev/null || echo '\e[0;33m')"
txtblu="$(tput setaf 4 2>/dev/null || echo '\e[0;34m')"
txtpur="$(tput setaf 5 2>/dev/null || echo '\e[0;35m')"
txtcyn="$(tput setaf 6 2>/dev/null || echo '\e[0;36m')"
txtwht="$(tput setaf 7 2>/dev/null || echo '\e[0;37m')"

bldblk="$(tput setaf 0 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;30m')"
bldred="$(tput setaf 1 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;31m')"
bldgrn="$(tput setaf 2 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;32m')"
bldylw="$(tput setaf 3 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;33m')"
bldblu="$(tput setaf 4 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;34m')"
bldpur="$(tput setaf 5 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;35m')"
bldcyn="$(tput setaf 6 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;36m')"
bldwht="$(tput setaf 7 2>/dev/null)$(tput bold 2>/dev/null || echo '\e[1;37m')"

undblk="$(tput setaf 0 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;30m')"
undred="$(tput setaf 1 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;31m')"
undgrn="$(tput setaf 2 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;32m')"
undylw="$(tput setaf 3 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;33m')"
undblu="$(tput setaf 4 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;34m')"
undpur="$(tput setaf 5 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;35m')"
undcyn="$(tput setaf 6 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;36m')"
undwht="$(tput setaf 7 2>/dev/null)$(tput smul 2>/dev/null || echo '\e[4;37m')"

bakblk="$(tput setab 0 2>/dev/null || echo '\e[40m')"
bakred="$(tput setab 1 2>/dev/null || echo '\e[41m')"
bakgrn="$(tput setab 2 2>/dev/null || echo '\e[42m')"
bakylw="$(tput setab 3 2>/dev/null || echo '\e[43m')"
bakblu="$(tput setab 4 2>/dev/null || echo '\e[44m')"
bakpur="$(tput setab 5 2>/dev/null || echo '\e[45m')"
bakcyn="$(tput setab 6 2>/dev/null || echo '\e[46m')"
bakwht="$(tput setab 7 2>/dev/null || echo '\e[47m')"
