#!/bin/bash
#
#export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
#export PATH=$HOME/.local/lib/bin:$PATH
#export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH

source /usr/share/gazebo/setup.sh
