#!/bin/bash

# stuff specific to HMI

#export ROS_IP="192.168.100.66"
#export ROS_MASTER_URI="http://192.168.10.110:11311"
#export ROS_IP="192.168.10.25"
export ROS_MASTER_URI="http://localhost:11311"
#echo "ROS_IP: $ROS_IP"
#echo "ROS_MASTER_URI: $ROS_MASTER_URI"

# set PATH so it includes user's private bin directories
#export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# gazeebs
#export GAZEBO_MASTER_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' gazebo)
#export GAZEBO_MASTER_URI=$GAZEBO_MASTER_IP:11345

export PATH="/snap/bin:$PATH"

# ansible hacking script
alias ansible-test-module='$HOME/src/ansible/hacking/test-module -m'

export PATH=/usr/lib/ccache:$PATH
